import { ruleTester } from "../shared/rule-tester.ts";
import { noComments } from "./no-comments.ts";

ruleTester.run("no-comments", noComments, {
  valid: [
    "#!/usr/bin/env node\nexport const value = 1;",
    "// oxlint-disable-next-line no-console -- startup failure must reach the terminal\nconsole.error(error);",
    "/* eslint-disable no-console */\nconsole.error(error);",
    "// @ts-expect-error the fixture omits a required field\nconst value: User = {};",
    '/// <reference types="vite/client" />\nexport const value = 1;',
    "const value = /* #__PURE__ */ create();",
    "const value = /*@__PURE__*/ create();",
    "// oxfmt-ignore\nconst matrix = [1,0,0,1];",
    "/* v8 ignore next */\nif (ready) { run(); }",
    "const page = import(/* @vite-ignore */ path);",
    'const page = import(/* webpackChunkName: "page" */ "./page");',
    "/** @vitest-environment jsdom */\nexport const value = 1;",
    "/**\n * @jest-environment node\n */\nexport const value = 1;",
    {
      code: "/**\n * @param {string} name\n * @returns {string}\n */\nexport function greet(name) { return name; }",
      filename: "greet.mjs",
    },
    {
      code: "/** @typedef {{ id: string }} User */\nexport const users = [];",
      filename: "users.js",
    },
    {
      code: "/** @type {import('oxlint').OxlintConfig} */\nexport const config = {};",
      filename: "oxlint.config.mjs",
    },
    {
      code: "/**\n * @template T\n * @param {T[]} values\n */\nexport function first(values) { return values[0]; }",
      filename: "first.jsx",
    },
    {
      code: "// generated by codegen\nexport const value = 1;",
      options: [{ allow: ["^generated by codegen$"] }],
    },
  ],
  invalid: [
    { code: "// Read the value\nexport const value = 1;", errors: [{ messageId: "comment" }] },
    { code: "export const value = 1; // why\n", errors: [{ messageId: "comment" }] },
    { code: "/** The value. */\nexport const value = 1;", errors: [{ messageId: "comment" }] },
    {
      code: "/*\n * Explains the value.\n */\nexport const value = 1;",
      errors: [{ messageId: "comment" }],
    },
    {
      code: "// see oxlint-disable docs\nexport const value = 1;",
      errors: [{ messageId: "comment" }],
    },
    {
      code: "/** @param {string} name */\nexport function greet(name: string) { return name; }",
      filename: "greet.ts",
      errors: [{ messageId: "comment" }],
    },
    {
      code: "/** Greets a person by name. */\nexport function greet(name) { return name; }",
      filename: "greet.mjs",
      errors: [{ messageId: "comment" }],
    },
    {
      code: "/**\n * Greets a person.\n * @param name the person\n */\nexport function greet(name) { return name; }",
      filename: "greet.js",
      errors: [{ messageId: "comment" }],
    },
    {
      code: "// @type {string}\nexport const name = 'value';",
      filename: "name.js",
      errors: [{ messageId: "comment" }],
    },
    {
      code: "// first\n// second\nexport const value = 1;",
      errors: [{ messageId: "comment" }, { messageId: "comment" }],
    },
  ],
});
